import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import "./globals.css";
import Header from './Component/header/Header';
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "CreatE NexT ApP",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> 
        <Header/> 
        <ToastContainer />
      <main> {children}</main>
     
      </body>
    </html>
  );
}
